version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: unit-test-challenge
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes: 
      - pgdata:/data/postgres
  app:
    build: .
    container_name: fin_api_app
    ports: 
      - 3333:3333
      - 9229:9229
    restart: always
    volumes:
      - .:/usr/app

volumes: 
  pgdata:
    driver: local